name: Build Docker Image

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '.gitignore'
      - '.dockerignore'
      - '.README.md'
  pull_request:
    branches: [ master ]

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
    - user: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: build the Docker image
      run: |
        docker build -f Dockerfile -t 287451751279.dkr.ecr.ap-northeast-2.amazonaws.com:1.0.0 .
